import Head from 'next/head';
import Image from 'next/image';
import logo from '../assets/logo.png';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBars } from '@fortawesome/free-solid-svg-icons';

import { faChevronDown } from '@fortawesome/free-solid-svg-icons';

import FixedNavBar from '../components/FixedNavBar';
import MobileNav from '../components/MobileNav';
import {
  faYoutube,
  faFacebook,
  faTwitter,
  faInstagram,
  faDribbble,
} from '@fortawesome/free-brands-svg-icons';
import { useRef, useEffect, useState } from 'react';

export default function Home() {
  const [showFixedNav, setShowFixedNav] = useState(false);
  const [showMobileNav, setShowMobileNav] = useState(false);
  const scrollRef = useRef();
  useEffect(() => {
    const observer = new IntersectionObserver((entries, observer) => {
      const entry = entries[0];
      setShowFixedNav(entry.isIntersecting);
    });
    observer.observe(scrollRef.current);
  }, []);

  const showMenuClickHandler = () => {
    setShowMobileNav(true);
  };
  const hideMenuClickHandler = () => {
    setShowMobileNav(false);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        {/* {showFixedNav && <ScrollNav />} */}
        <FixedNavBar
          showFixedNav={showFixedNav}
          onShowMenu={showMenuClickHandler}
        />

        <div className="h-[1000px] bg-red-700"> section2</div>
        <div className="h-[1000px] bg-green-700" id="section3" ref={scrollRef}>
          section3
        </div>
        {showMobileNav && <MobileNav onHideMenu={hideMenuClickHandler} />}
      </>
    </div>
  );
}
