import Head from 'next/head';
import Image from 'next/image';
import logo from '../assets/logo.png';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBars } from '@fortawesome/free-solid-svg-icons';
import {
  faYoutube,
  faFacebook,
  faTwitter,
  faInstagram,
  faDribbble,
} from '@fortawesome/free-brands-svg-icons';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <nav>
          <div className="navContainer">
            <div className="logo">
              <a>
                <Image
                  src={logo}
                  alt="Sandbox"
                  // width={500} automatically provided
                  // height={500} automatically provided
                  // blurDataURL="data:..." automatically provided
                  // placeholder="blur" // Optional blur-up while loading
                />
              </a>
            </div>
            <div className="collapsibleItems"></div>
            <div className="socials">
              <ul>
                <li>
                  <nav>
                    <a href="">
                      <FontAwesomeIcon icon={faTwitter} />
                    </a>
                    <a href="">
                      <FontAwesomeIcon icon={faFacebook} />
                    </a>
                    <a href="">
                      <FontAwesomeIcon icon={faDribbble} />
                    </a>
                    <a href="">
                      <FontAwesomeIcon icon={faInstagram} />
                    </a>
                  </nav>
                </li>
                <li>
                  <FontAwesomeIcon icon={faBars} />
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div></div>
        <footer></footer>
      </>
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
